[tools]
python = "3.11"
uv = "0.6.16"
"ubi:B1NARY-GR0UP/nwa" = "latest"

[settings]
experimental = true # for python.uv_venv_auto
python.uv_venv_auto = true
raw = true

## grouped tasks

[tasks."setup"]
depends = ["setup:*"]

[tasks."check"]
depends = ["*:check"]

[tasks."fix"]
depends = ["*:fix"]

## repo setup

[tasks."setup:mise-local-toml"]
hide = true
dir = "{{config_root}}"
run = "test -f mise.local.toml || cp mise.local.toml-example mise.local.toml"
sources = ["mise.local.toml-example"]
outputs = { auto = true }

# [tasks."setup:uv"]
# hide = true
# dir = "{{config_root}}"
# run = "uv sync --all-extras --dev"
# sources = ["uv.lock", "pyproject.toml", "apps/*/pyproject.toml"]
# outputs = { auto = true }

## common tasks

### check

[tasks."common:check"]
depends = ["common:check:*"]

[tasks."common:check:nwa"]
dir = "{{config_root}}"
run = "nwa check -i Apache-2.0 -c '© BeeAI a Series of LF Projects, LLC' '*/src/**/*.{py,js,jsx,ts,tsx,html,css,scss}'"
# sources don't support {a,b} -- https://github.com/jdx/mise/discussions/4469
sources = ["*/src/**/*.py", "*/src/**/*.js", "*/src/**/*.jsx", "*/src/**/*.ts", "*/src/**/*.tsx", "*/src/**/*.html", "*/src/**/*.css", "*/src/**/*.scss"]
outputs = { auto = true }

### fix

[tasks."common:fix"]
depends = ["common:fix:*"]

[tasks."common:fix:nwa"]
dir = "{{config_root}}"
run = """
nwa update -i Apache-2.0 -c '© BeeAI a Series of LF Projects, LLC' '*/src/**/*.{py,js,jsx,ts,tsx,html,css,scss}' --mute || true
nwa add    -i Apache-2.0 -c '© BeeAI a Series of LF Projects, LLC' '*/src/**/*.{py,js,jsx,ts,tsx,html,css,scss}' --mute || true
"""
# sources don't support {a,b} -- https://github.com/jdx/mise/discussions/4469
sources = ["*/src/**/*.py", "*/src/**/*.js", "*/src/**/*.jsx", "*/src/**/*.ts", "*/src/**/*.tsx", "*/src/**/*.html", "*/src/**/*.css", "*/src/**/*.scss"]
outputs = { auto = true }
